### ISSUE TITLE
Exécutable Windows

### ISSUE THREAD

**Issue by Olivier-75706** [Lully/bnf-sru#1]
L'exécutable Windows n'est plus disponible sur Google Drive.
Serait-il possible de mettre le lien à jour ?
Merci beaucoup.

**Comment by Lully** [comment]
De quel programme s'agit-il ? (j'ai plein de petits scripts partout dans ce dossier)

**Comment by Olivier-75706** [comment]
Il s'agit du script ExtractionCatalogueBnF.

**Comment by Lully** [comment]
Je viens de verser une 1.11 compilée pour Windows  https://github.com/Lully/bnf-sru/blob/master/bin/ExtractionCatalogueBnF_1.11_win64_py3.6.zip, qui me semble fonctionner

**Comment by Olivier-75706** [comment]
C'est parfait, merci pour ce script et pour votre réactivité.
